package org.znk.handson.jigsaw.api.local.impl;

import org.znk.handson.jigsaw.api.CharactersApi;
import org.znk.handson.jigsaw.api.MarvelCharacter;

import java.util.*;
import java.util.stream.Collectors;
import static java.util.Map.entry;


public class InMemoryCharactersApi implements CharactersApi {

    /**
     * Find the Character by is id
     *
     * Data provided by Marvel. © 2014 Marvel
     * https://developer.marvel.com
     * @param id of the character
     * @return the character if the id exist
     */
    @Override
    public Optional<MarvelCharacter> find(int id) {
        return Optional.ofNullable(charactersAsMap.get(id));
    }

    /**
     * Find all the Characters
     * Data provided by Marvel. © 2014 Marvel
     * https://developer.marvel.com
     * @return All the characters
     */
    @Override
    public List<MarvelCharacter> findAll() {
        return charactersAsList;
    }


    /**
     * Find all the Characters containing name ignoring case
     * @param name the name (or part of the name) for searching
     * @return All the characters that contains the name
     */
    @Override
    public List<MarvelCharacter> findByNameContaining(String name) {
        if (null == name || name.isEmpty()) {
            return findAll();
        }
        final String lowerName = name.toLowerCase();
        return charactersAsList.stream().filter(c -> c.name.toLowerCase().contains(lowerName)).collect(Collectors.toList());
    }


    // Data provided by Marvel. © 2014 Marvel
    // Marvel Developper Portal https://developer.marvel.com
    // curl & jq & bash have super power too
    private static final Map<Integer, MarvelCharacter> charactersAsMap =
            Map.ofEntries(
                    entry(1009144, new MarvelCharacter(1009144, "A.I.M.", "AIM is a terrorist organization bent on destroying the world.")),
                    entry(1010354, new MarvelCharacter(1010354, "Adam Warlock", "Adam Warlock is an artificially created human who was born in a cocoon at a scientific complex called The Beehive.")),
                    entry(1010755, new MarvelCharacter(1010755, "Alex Wilder", "Despite being the only one of the Runaways without any superhuman abilities or tech, Alex Wilder became the de facto leader of the group due to his natural leadership skills and intellect, as well as prodigy-level logic and strategy.")),
                    entry(1010905, new MarvelCharacter(1010905, "Amun", "Amun is a ruthless teenage assassin, employed by the Sisterhood of the Wasp to serve under the mage Vincent after Araña interrupted the ritual to initiate the Wasp's new chosen one.")),
                    entry(1009740, new MarvelCharacter(1009740, "Arnim Zola", "The frail, dwarfish Arnim Zola was born in 1930s Switzerland where he became the world's leading biochemist and genetic engineer.")),
                    entry(1009165, new MarvelCharacter(1009165, "Avengers", "Earth's Mightiest Heroes joined forces to take on threats that were too big for any one hero to tackle. With a roster that has included Captain America, Iron Man, Ant-Man, Hulk, Thor, Wasp and dozens more over the years, the Avengers have come to be regarded as Earth's No. 1 team.")),
                    entry(1011346, new MarvelCharacter(1011346, "Ben Reilly", "Ben Reilly was the most genetically stable of the many clones of Spider-Man created by Professor Miles Warren, the Jackal.")),
                    entry(1010782, new MarvelCharacter(1010782, "Ben Urich", "Ben Urich is a reporter for the Daily Bugle who has many ties to the city's superhero community.")),
                    entry(1011119, new MarvelCharacter(1011119, "Bob, Agent of Hydra", "A cowardly young man, Bob was persuaded into joining the criminal organization HYDRA and has had numerous encounters with Deadpool and other Marvel heroes.")),
                    entry(1010366, new MarvelCharacter(1010366, "Boom Boom", "When Tabitha Smith's mutant nature manifested at age 13, she ran away from her abusive home and eventually hooked up with the New Mutants and, subsequently, X-Force.")),
                    entry(1011276, new MarvelCharacter(1011276, "Cap'n Oz", "William was born into the ClanDestine, making him a creature that is part magic. After events surrounding the death of his brother Vincent, he moved to Australia where he started an acting career as the superhero Cap'n Oz.")),
                    entry(1009220, new MarvelCharacter(1009220, "Captain America", "Vowing to serve his country any way he could, young Steve Rogers took the super soldier serum to become America's one-man army. Fighting for the red, white and blue for over 60 years, Captain America is the living, breathing symbol of freedom and liberty.")),
                    entry(1009225, new MarvelCharacter(1009225, "Captain Stacy", "NYPD Captain George Stacy was the father of one-time Peter Parker girlfriend Gwen Stacy.")),
                    entry(1009688, new MarvelCharacter(1009688, "Carmella Unuscione", "Carmella Unuscione was one of the first members of the Magneto's Acolytes.")),
                    entry(1010754, new MarvelCharacter(1010754, "Chase Stein", "Chase Stein is the son of mad scientists Victor and Janet Stein and is the tech genius of the Runaways.")),
                    entry(1010676, new MarvelCharacter(1010676, "Colleen Wing", "Colleen Wing was raised in Japan by her grandfather Kanji Ozawa, who taught her the ways of a samurai, in which she became highly skilled, after which she teamed up with Misty Knight at the behest of Tony Stark as a new Heroes for Hire tasked with capturing superhumans who have not registered.")),
                    entry(1009262, new MarvelCharacter(1009262, "Daredevil", "Abandoned by his mother, Matt Murdock was raised by his father, boxer 'Battling Jack' Murdock, in Hell's Kitchen. Realizing that rules were needed to prevent people from behaving badly, young Matt decided to study law; however, when he saved a man from an oncoming truck, it spilled a radioactive cargo that rendered Matt blind while enhancing his remaining senses. Under the harsh tutelage of blind martial arts master Stick, Matt mastered his heightened senses and became a formidable fighter.")),
                    entry(1010890, new MarvelCharacter(1010890, "Deathlok", "&nbsp;")),
                    entry(1011071, new MarvelCharacter(1011071, "Demogoblin", "Jason Macendale, the newest Hobgoblin was down on his luck and offered the demon N'astirh his soul in exchange for power during the Inferno crisis, turning him into the Demogoblin.")),
                    entry(1009297, new MarvelCharacter(1009297, "Falcon", "With a mental connection to all birds and a suit that gives him wings to fly, The Falcon has been both the partner to Captain America and an Avenger himself. Whether as a super hero or in his secret identity of social worker Sam Wilson, The Falcon dedicates his life to standing up for others.")),
                    entry(1009299, new MarvelCharacter(1009299, "Fantastic Four", "After being exposed to cosmic rays, Reed Richards, Susan Storm, Ben Grimm and Johnny Storm found they had amazing new powers. Reed Richards found he has the ability to stretch his body in any way he wanted, while Susan Storm can turn herself, objects and other people invisible. Ben Grimm transformed into a rocky, super-strong behemoth and Johnny Storm has the ability to set himself on fire. Dubbed the Fantastic Four, Mr. Fantastic, Invisible Woman, Thing and the Human Torch are Marvel's First Family.")),
                    entry(1009539, new MarvelCharacter(1009539, "Franklin Richards", "The son of Reed Richards and Susan Storm of the Fantastic Four, Franklin may one day be the most powerful person on Earth. Right now, he's the son of a genius who finds adventure and fun around every corner.")),
                    entry(1010980, new MarvelCharacter(1010980, "Franklin Storm", "Franklin Storm was the father of Susan and Johnny Storm.")),
                    entry(1009645, new MarvelCharacter(1009645, "Glenn Talbot", "Major Glenn Talbot was member of United States Air Force, United States Army and Hulkbusters.")),
                    entry(1011299, new MarvelCharacter(1011299, "Guardians of the Galaxy", "A group of cosmic adventurers brought together by Star-Lord, the Guardians of the Galaxy protect the universe from threats all across space. The team also includes Drax, Gamora, Groot and Rocket Raccoon!")),
                    entry(1009619, new MarvelCharacter(1009619, "Gwen Stacy", "Peter Parker's first true love, Gwen Stacy was killed during a rescue attempt by Spider-Man, the guilt from which Peter has never overcome.")),
                    entry(1009351, new MarvelCharacter(1009351, "Hulk", "Caught in a gamma bomb explosion while trying to save the life of a teenager, Dr. Bruce Banner was transformed into the incredibly powerful creature called the Hulk. An all too often misunderstood hero, the angrier the Hulk gets, the stronger the Hulk gets.")),
                    entry(1009368, new MarvelCharacter(1009368, "Iron Man", "Wounded, captured and forced to build a weapon by his enemies, billionaire industrialist Tony Stark instead created an advanced suit of armor to save his life and escape captivity. Now with a new outlook on life, Tony uses his money and intelligence to make the world a safer, better place as Iron Man.")),
                    entry(1011105, new MarvelCharacter(1011105, "Jimmy Woo", "Jimmy Woo is a former FBI and SHIELD agent from the '50s who now leads the Agents of Atlas in the present.")),
                    entry(1009721, new MarvelCharacter(1009721, "John Wraith", "A mutant with teleportation powers, Wraith served with Wolverine, Sabretooth, Maverick and Silver Fox in Team X, a covert operations unit formed by Weapon X.")),
                    entry(1011319, new MarvelCharacter(1011319, "Ken Ellis", "Former Daily Bugle and current DB! reporter Ken Ellis first made a splash during the public debut of Ben Reilly as the Scarlet Spider, providing the new costumed hero with his name following a pitched battle with Venom.")),
                    entry(1009735, new MarvelCharacter(1009735, "Mariko Yashida", "Mariko Yashida was the daughter of Japanese crimelord Lord Shingen, leader of Clan Yashida, and one-time fiance of Wolverine.")),
                    entry(1009708, new MarvelCharacter(1009708, "Mary Jane Watson", "Mary Jane Watson was the guiding light in Peter Parker's life, and their love had overcome countless obstacles.")),
                    entry(1009677, new MarvelCharacter(1009677, "Matsu'o Tsurayaba", "Tsurayaba became leader of a faction of the ninja clan the Hand, finding himself at odds with his lover Kwannon who was an assassin for rival crimelord Nyoirin.")),
                    entry(1009439, new MarvelCharacter(1009439, "Meltdown", "When Tabitha Smith's mutant nature manifested at age 13, she ran away from her abusive home before eventually hooking up with the New Mutants and, subsequently, X-Force.")),
                    entry(1013727, new MarvelCharacter(1013727, "Miracleman", "Michael Moran has a superhuman alter ego. By saying the trigger word 'Kimota!' Michael turns into Miracleman! But is the good of being Miracleman enough to outweigh the cost?")),
                    entry(1010779, new MarvelCharacter(1010779, "Pete Wisdom", "Pete Wisdom is a former agent of the British intelligence agency Black Air, which was charged with the observation of, and interaction with, extranormal activity, and he was the agency's liaison with the British superhero group Excalibur, whom he eventually aided in exposing Black Air's subversive criminal activities.")),
                    entry(1010744, new MarvelCharacter(1010744, "Rocket Raccoon", "A genetically-engineered alien with a knack for big guns and fast ships, Rocket serves as the backbone of the Guardians of the Galaxy!")),
                    entry(1010747, new MarvelCharacter(1010747, "Runaways", "The teens who became the Runaways found that some family secrets are bigger than others when they witnessed their parents, part of a cabal known as the Pride, murdering a young girl during a secret sacrificial ritual.")),
                    entry(1009553, new MarvelCharacter(1009553, "Sabra", "Ruth Bat-Seraph is an Israeli national who, along with her family, was taken to a special community by the Israeli government when her genetic mutation manifested.")),
                    entry(1011230, new MarvelCharacter(1011230, "Scrambler", "Korean national Kim Il Sung was the youngest member of the Marauders, the superhuman assassins responsible for massacring the underground mutant community known as the Morlocks.")),
                    entry(1011242, new MarvelCharacter(1011242, "Screwball", "Trained in parkour, Screwball, fairly new to the New York City superhuman criminal community, specializes in recording he crimes and broadcasting them live over the internet.")),
                    entry(1009581, new MarvelCharacter(1009581, "Sebastian Shaw", "Sebastian Shaw was invited to join the elite Hellfire Club and quickly worked his way into a position within the Inner Circle.")),
                    entry(1009568, new MarvelCharacter(1009568, "Selene", "The long-standing Black Queen of the Hellfire Club's Inner Circle, Selene Gallio professes to have lived for several millennia, and to have been a foe of the ancient sorcerer, Kulan Gath.")),
                    entry(1010345, new MarvelCharacter(1010345, "Sersi", "Sersi is a member of the Eternals, a species diverted from humanity by experiments conducted by the Celestials one million years ago.")),
                    entry(1009573, new MarvelCharacter(1009573, "Shadow King", "One of the oldest and more powerful mutants ever, Amahl Farouk has been a threat to mankind at least for decades. He was the first evil mutant met by Charles Xavier, convincing him of the need of the X-Men.")),
                    entry(1011406, new MarvelCharacter(1011406, "Shadu the Shady", "Shadu the Shady claimed to travel to many unseen magical lands and witnessed miracles he would duplicate at a club called the 53rd Card.")),
                    entry(1009576, new MarvelCharacter(1009576, "Shaman", "Dr. Michael Twoyoungmen was a surgeon who found that modern science was insufficient to accomplish everything he wished to do, and so he turned to mysticism that his grandfather told him about.")),
                    entry(1009577, new MarvelCharacter(1009577, "Shang-Chi", "Shang-Chi is the son of an internationally-renowned and powerful criminal mastermind whose childhood was a lonely one, full of constant training in rigorous mental and martial arts, with only limited contact with his parents.")),
                    entry(1009578, new MarvelCharacter(1009578, "Shanna the She-Devil", "The only daughter of a wealthy diamond miner, Shanna grew up in the Zaire jungles, where, at age six, she witnessed her father’s accidental fatal shooting of her mother, starting a lifelong loathing of firearms.")),
                    entry(1010712, new MarvelCharacter(1010712, "Shape", "Often clashing with the heroes of the Squadron Supreme, the Shape was later subjected to the mind-altering behavior modification device used as part of the Squadron Supreme's 'Utopia Program.'")),
                    entry(1009579, new MarvelCharacter(1009579, "Shard", "Shard and her older brother Bishop were raised in the 21st Century, some eighty years into an alternate future, by their grandmother, in a timeline in which the X-Men were betrayed by one of their own and killed, causing a disaster that caused the government to place a stylized 'M' tattoo over the left eyes of all mutants.")),
                    entry(1009580, new MarvelCharacter(1009580, "Shatterstar", "Shatterstar is Gaveedra Seven, the product of bio-engineering on an otherdimensional world, who was at one point merged with an Earth mutant named Benjamin Russell, the nature of whose genetic mutation remains unknown.")),
                    entry(1009582, new MarvelCharacter(1009582, "Shinobi Shaw", "Shinobi Shaw is the illegitimate son of Sebastian Shaw, who was rejected and abandoned by his father at an early age and grew tired of waiting to inherit his father's wealth and wearied of the elder Shaw's contempt for his decadent lifestyle.")),
                    entry(1011394, new MarvelCharacter(1011394, "Shiver Man", "The Shiver Man is an undead bounty hunter who has worked with Nick Fury and Wolverine.")),
                    entry(1010858, new MarvelCharacter(1010858, "Shockwave", "Lancaster Sneed was a secret agent working for the United Kingdom’s MI:6, but no one esteemed him as highly as himself, and despite his pride, he was wounded in an explosion on his first field assignment and forced to undergo a radical surgery that grafted metal plates and cybernetic systems to his body.")),
                    entry(1009587, new MarvelCharacter(1009587, "Shriek", "Shriek became a groupie for a rock band and a drug dealer on the side until the vigilantes Cloak and Dagger happened by during one of her deals.")),
                    entry(1009588, new MarvelCharacter(1009588, "Sif", "Sif was born a second generation goddess of Asgard and eventually became Thor's lover.")),
                    entry(1010848, new MarvelCharacter(1010848, "Silhouette", "Silhouette Chord is a descendant of the Dragon's Breadth cult, which spent centuries trying to master the Well of All Things, a hidden interdimensional mystic energy breach in Cambodia.")),
                    entry(1009589, new MarvelCharacter(1009589, "Silver Fox", "Silver Fox was a young member of the Blackfoot Indian tribe who, in the early 1910s, fell in love with a young mutant named Logan and shared a cabin with him in a remote community in the Canadian Rockies.")),
                    entry(1009590, new MarvelCharacter(1009590, "Silver Sable", "Silver Sable trained her entire life, becoming a master of a wide variety of weapons and training in all forms of hand-to-hand combat in preparation for the day she would inherit leadership of the Wild Pack.")),
                    entry(1009591, new MarvelCharacter(1009591, "Silver Samurai", "Keniuchio Harada is the mutant son of the former Japanese crimelord Shingen Harada.")),
                    entry(1009592, new MarvelCharacter(1009592, "Silver Surfer", "When Zenn-La was threatened by the world-devouring entity known as Galactus, Norrin Radd stood up for his home planet and offered to work for Galactus, finding him new planets to eat, in exchange for saving his own. Years later, the Surfer has protected Earth and many other planets, becoming one of the greatest heroes in the universe.")),
                    entry(1010864, new MarvelCharacter(1010864, "Silverclaw", "When her father died, Lupe was taken in by the Church orphanage, despite their misgivings about her “ungodly” powers.")),
                    entry(1009594, new MarvelCharacter(1009594, "Silvermane", "Silvio Manfredi has been a career criminal for most of his life.")),
                    entry(1011223, new MarvelCharacter(1011223, "Skaar", "The Hulk fathered a son while on the planet Sakaar, but thought him killed while still in his mother's womb; he was wrong.")),
                    entry(1009598, new MarvelCharacter(1009598, "Skin", "Angelo Espinosa, a founding member of Generation X, code-named 'Skin' due to his mutant ability to extend and control his extra skin in any number of ways.")),
                    entry(1011157, new MarvelCharacter(1011157, "Skreet", "The Proemial God Aegis revealed that Skreet was a Chaos Mite, a race of very small and powerful beings, which were deemed unstable by the Cosmic Consonance.")),
                    entry(1011057, new MarvelCharacter(1011057, "Slapstick", "Steven Harmon's powers have been described as 'all of the abilities of a Saturday morning cartoon character.'")),
                    entry(1011070, new MarvelCharacter(1011070, "Slayback", "Ten years ago, Slayback was killed by Deadpool before returning from the dead to break into Department K, from which he stole the Weapon X Program files of Kane and Deadpool.")),
                    entry(1010761, new MarvelCharacter(1010761, "Sleepwalker", "Sleepwalkers are guardians of the Mindscape -- they apprehended beings that invade the sleeping minds of humans.")),
                    entry(1009602, new MarvelCharacter(1009602, "Slipstream", "Australian mutant siblings Heather and Davis Cameron were sent to live in Surfer's Paradise by their father in an effort to spare them from his life as Viceroy, godfather of Australian organized crime.")),
                    entry(1010874, new MarvelCharacter(1010874, "Slyde", "A scientist at Beemont Manufacturing, Jalome Beacher created a chemical that could be used to coat a surface and thereby eliminate all friction between it and any other object, which he used, after being downsized, to rob banks and his former employers.")),
                    entry(1009606, new MarvelCharacter(1009606, "Snowbird", "Narya's origins trace back to ancient times when the Eskimo Gods of the North battled the mystical Great Beasts for the fate of the world.")),
                    entry(1010693, new MarvelCharacter(1010693, "Songbird", "Melissa Gold grew up on the streets, adopting her mother's name 'Mimi' as part of a hard, cold persona she developed as a survival mechanism.")),
                    entry(1010833, new MarvelCharacter(1010833, "Speed", "Tommy Shepherd may be the son of the Scarlet Witch and the Vision, and thus the twin brother of Wiccan.")),
                    entry(1011032, new MarvelCharacter(1011032, "Speed Demon", "James Saunders, a disgruntled chemist tired of his job with the Hudson Pharmaceutical Company of West Caldwell, New Jersey, was contacted by the Grandmaster and offered superhuman powers in exchange for joining a team that would compete on his behalf.")),
                    entry(1009610, new MarvelCharacter(1009610, "Spider-Man", "Bitten by a radioactive spider, high school student Peter Parker gained the speed, strength and powers of a spider. Adopting the name Spider-Man, Peter hoped to start a career using his new abilities. Taught that with great power comes great responsibility, Spidey has vowed to use his powers to help people.")),
                    entry(1011158, new MarvelCharacter(1011158, "Spirit", "Spirit is a member of the Luphomoid race and she is one of the few survivors of her planet's destruction.")),
                    entry(1010899, new MarvelCharacter(1010899, "Spitfire", "During World War II, Jacqueline Falsworth bravely served in Britain’s Home Guard.")),
                    entry(1009616, new MarvelCharacter(1009616, "Spot", "Jonathan Ohnn was working as a research scientist on behalf of Wilson Fisk, the Kingpin of Crime.")),
                    entry(1011180, new MarvelCharacter(1011180, "Sprite", "Sprite is a mischievous Eternal who maintains a perpetual youthful appearance.")),
                    entry(1010860, new MarvelCharacter(1010860, "Squirrel Girl", "Escaping the taunts of her fellow school students regarding her physical mutation, Los-Angeles born Doreen Green fled into the nearby woods where she quickly discovered her affinity for squirrels.")),
                    entry(1009621, new MarvelCharacter(1009621, "Starbolt", "Starbolt is a member of the Shi'ar Imperial Guard.")),
                    entry(1010764, new MarvelCharacter(1010764, "Stardust", "As Herald for the world devourer, Galactus, Stardust found suitable worlds for her master to consume.")),
                    entry(1011084, new MarvelCharacter(1011084, "Starfox", "The youngest son of Mentor and Sui-San, Eros had the natural ability to excite pleasure in others, but his power had no effect upon his mutant older brother, Thanos, who worshiped the cosmic embodiment of Death and led an army against Titan.")),
                    entry(1010828, new MarvelCharacter(1010828, "Stature", "Cassie Lang is the daughter of deceased Avenger Scott Lang and a member of the Young Avengers.")),
                    entry(1011159, new MarvelCharacter(1011159, "Stellaris", "It is unknown how Stellaris survived the extermination of her home world by the Celestials or how she acquired her living armor, but ever since she has committed herself to their destruction.")),
                    entry(1009625, new MarvelCharacter(1009625, "Stepford Cuckoos", "The Stepford Cuckoos were five identical mutant sisters who enrolled at the Xavier Institute and soon proved to be the crème de la crème of Emma Frost's telepathy class.")),
                    entry(1009626, new MarvelCharacter(1009626, "Stick", "Stick, who trained both Daredevil and Elektra in the martial arts, is the leader of the warrior order called The Chaste, and has fought alongside the clan's other members against The Hand for years.")),
                    entry(1009629, new MarvelCharacter(1009629, "Storm", "Ororo Monroe is the descendant of an ancient line of African priestesses, all of whom have white hair, blue eyes, and the potential to wield magic.")),
                    entry(1011062, new MarvelCharacter(1011062, "Stranger", "By his own account, the Stranger is a composite being possessing the combined strength and intellect of the billions of humanoid beings who once lived on the planet Gigantus, an ancient world in the Andromeda Galaxy whose size approached the limit at which a planet can exist before fissioning into a sun.")),
                    entry(1011051, new MarvelCharacter(1011051, "Strong Guy", "According to his own admission, Guido was a nerdy-looking kid in his early life, bullied by other children, but after he discovered his mutant ability at a young age, when he was struck by a school bus, no one bullied him again.")),
                    entry(1009632, new MarvelCharacter(1009632, "Stryfe", "Stryfe is the clone of Nathan Christopher Summers, alias Cable, the son of Cyclops of the X-Men.")),
                    entry(1010791, new MarvelCharacter(1010791, "Sub-Mariner", "Prince Namor is the half-human/half-Atlantean ruler of Atlantis.")),
                    entry(1011212, new MarvelCharacter(1011212, "Sugar Man", "The Sugar Man was in charge of the Seattle Core, a slave camp that helped power North America during the Age of Apocalypse.")),
                    entry(1009636, new MarvelCharacter(1009636, "Sunfire", "Shiro Yoshida’s mother was exposed to the atomic devastation of Hiroshima during World War II and died giving birth to him.")),
                    entry(1009638, new MarvelCharacter(1009638, "Sunspot", "Growing up in a wealthy Brazilian family, Roberto da Costa was forging a career as a skilled soccer player until his mutant nature manifested during a match.")),
                    entry(1011022, new MarvelCharacter(1011022, "Super-Adaptoid", "The Super-Adaptoid was created by the organization known as A.I.M. using a piece of the Cosmic Cube.")),
                    entry(1009639, new MarvelCharacter(1009639, "Super-Skrull", "After the Fantastic Four stopped the Skrulls' attempted invasion of Earth, Skrull Emperor Dorrek invested vast resources into creating a superbeing of his own.")),
                    entry(1011232, new MarvelCharacter(1011232, "Supernaut", "Sergeant Milo Fields was recruited for the Order and regained the use of his legs after his nervous system intermingled with that of Aralune.")),
                    entry(1011160, new MarvelCharacter(1011160, "Supreme Intelligence", "The Supreme Intelligence is an organic, computer construct, created by the Kree to act as their supreme leader.")),
                    entry(1010695, new MarvelCharacter(1010695, "Surge", "Prior to enrolling at the Xavier Institute, Noriko Ashida lived on the street and was reliant on illegally obtained prescription drugs to reduce her highly accelerated mutant brain functions to a manageable rate.")),
                    entry(1011075, new MarvelCharacter(1011075, "Swarm", "Fritz von Meyer was once a Nazi scientist, the details of which remain unrevealed, although it is known he had access to looted gold from countless European capitals to fund his research.")),
                    entry(1011017, new MarvelCharacter(1011017, "Sway", "Suzanne Chan saw her parents gunned down in front of her, though she remained unscathed due to her manifesting mutant ability to stop time.")),
                    entry(1009641, new MarvelCharacter(1009641, "Swordsman", "Andreas reappeared as the Swordsman in the latest incarnation of the Thunderbolts, though his true identity was kept secret for some time.")),
                    entry(1009643, new MarvelCharacter(1009643, "Synch", "Everett Thomas was a founding member of Generation X.")),
                    entry(1011161, new MarvelCharacter(1011161, "Talos", "Born without the ability to shape shift like other Skrulls, Talos became a savage fighter and a decorated military commander.")),
                    entry(1009648, new MarvelCharacter(1009648, "Taskmaster", "Taskmaster first exhibited his unusual ability, called 'photographic reflexes,' which allowed him to mimic the motion of anyone he saw, when he was a young boy.")),
                    entry(1011162, new MarvelCharacter(1011162, "Tenebrous", "Tenebrous has existed in this universe since its infancy, and was imprisoned in the planet Kyln after a battle with Galactus.")),
                    entry(1009651, new MarvelCharacter(1009651, "Terrax", "Tyros was once the dictator of the city Lanlak on the planet Birj, where his superhuman ability to command rocks and earth enabled him to overcome all resistance, but his rule of Lanlak came to an end when he was sought by the world-devouring Galactus to serve as his latest Herald.")),
                    entry(1011034, new MarvelCharacter(1011034, "Terror", "In the distant past, Terror battled a green bear-like demon that threatened early mankind, sacrificing his own form to overcome it; he was then cursed to wear its decayed form but gained its power.")),
                    entry(1009652, new MarvelCharacter(1009652, "Thanos", "The Mad Titan Thanos, a melancholy, brooding individual, consumed with the concept of death, sought out personal power and increased strength, endowing himself with cybernetic implants until he became more powerful than any of his brethren.")),
                    entry(1011181, new MarvelCharacter(1011181, "Thena", "Thena, a second generation Eternal, is the eldest daughter of Zuras, leader of the Eternals of Earth, and Cybele, and although she has lived for more than 4,000 years, she is still considered a young woman by Eternal standards.")),
                    entry(1009662, new MarvelCharacter(1009662, "Thing", "The radiation that mutated Reed Richards, Sue Storm and Johnny Storm into superhuman beings had also mutated Ben Grimm, transforming him into a grotesque, rock-hided strongman dubbed the Thing.")),
                    entry(1009664, new MarvelCharacter(1009664, "Thor", "As the Norse God of thunder and lightning, Thor wields one of the greatest weapons ever made, the enchanted hammer Mjolnir. While others have described Thor as an over-muscled, oafish imbecile, he's quite smart and compassionate. He's self-assured, and he would never, ever stop fighting for a worthwhile cause.")),
                    entry(1010820, new MarvelCharacter(1010820, "Thor Girl", "Tarene, aware of her true nature as the Designate, a being foretold to elevate all life to greatness, sought adventure and, using Thor as a template, transformed herself into an Asgardian goddess and journeyed to Earth.")),
                    entry(1010885, new MarvelCharacter(1010885, "Thunderball", "Dr. Eliot Franklin was a genius-level physicist who was forced to turn to crime and helped form the Wrecking Crew alongside the Wrecker, Bulldozer and Piledriver.")),
                    entry(1010360, new MarvelCharacter(1010360, "Thunderbolts", "After a battle with Onslaught left the world without the majority of the heroes that made it feel safe, Baron Zemo devised a plan like no other in order to rule the world. Zemo gathered Beetle, Fixer, Goliath, Moonstone, and Screaming Mimi, all former members of the Masters of Evil, together to disguise themselves as a new heroic team in order to take advantage of the missing heroes and gain the trust of the authorities and public in general.")),
                    entry(1011304, new MarvelCharacter(1011304, "Thundra", "Thundra was quite possibly her world's greatest female specimens, and as she won countless battles against the men, she was revered as the Sisterhood's greatest hero.")),
                    entry(1009669, new MarvelCharacter(1009669, "Tiger Shark", "A champion Olympic swimmer, Todd Arliss earned nearly half million dollars in advances for public exhibitions, but his dreams came crashing down around him when he injured his back and legs while rescuing a man who had fallen overboard from a private craft, sending Arliss into the arms of Dr. Lemuel Dorcas, who used his 'morphotron,' which could imprint the genetic pattern of an animal onto a human, turning Arliss into a superhuman, amphibious creature.")),
                    entry(1010857, new MarvelCharacter(1010857, "Timeslip", "As a young child, Rina Patel experienced visions of her future, though she eventually learned to control this, triggering visions of specific times, and she realized she was swapping her consciousness across time.")),
                    entry(1011345, new MarvelCharacter(1011345, "Tinkerer", "The Tinkerer is an ordinary man who has an extraordinary talent for anything mechanical.")),
                    entry(1011960, new MarvelCharacter(1011960, "Tippy Toe", "After the senseless murder of Squirrel Girl’s first partner Monkey Joe, Tippy Toe remained by Squirrel Girl’s side and became her new partner.")),
                    entry(1010669, new MarvelCharacter(1010669, "Titania", "Despondent and hopeless after it was discovered that she was not, in fact, Spider-Woman, Mary MacPherran encountered Doctor Doom, who offered her a chance to become superpowered in exchange for joining his army, to which Mary readily agreed, and Doom transformed her into Titania.")),
                    entry(1009673, new MarvelCharacter(1009673, "Toad", "British-born Mortimer Toynbee, abandoned by his parents so early in childhood that he cannot remember them, was placed in an orphanage where the other children, who regarded him as a freak due to his ugliness, his unusual physique and his leaping ability, continually tormented him.")),
                    entry(1009675, new MarvelCharacter(1009675, "Tombstone", "Known as Tombstone, Lonnie Lincoln filed his teeth to points to add to his already intimidating image and honed his fighting skills in numerous street fights.")),
                    entry(1009676, new MarvelCharacter(1009676, "Toxin", "NYPD Officer Patrick Mulligan was implanted with a symbiote offspring during a chance encounter with Carnage.")),
                    entry(1010822, new MarvelCharacter(1010822, "Trauma", "Terrance Ward was drafted into the Initiative training program because of his telepathic and shape-shifting abilities.")),
                    entry(1010825, new MarvelCharacter(1010825, "Triathlon", "After being exposed as a steroid user and stripped of his awards, gifted sprinter Delroy Garrett Jr. sought new direction in the Triune Understanding, a philosophical movement that preaches the fulfillment of one's innate potential by balancing various aspects of environment and self, after which he developed a superhuman triple-powered physique, and, believing the Triune teachings had unlocked his latent powers, Garrett became the costumed hero Triathlon and celebrity spokesman for the Triune Understanding.")),
                    entry(1010335, new MarvelCharacter(1010335, "Triton", "Triton is a member of the Inhumans.")),
                    entry(1011047, new MarvelCharacter(1011047, "Turbo", "As Turbo, young journalist Michiko Musashi is the latest in a line of heroes who have worn the turbine-powered flying armor.")),
                    entry(1010369, new MarvelCharacter(1010369, "Typhoid Mary", "Typhoid Mary, an enemy and former lover of Daredevil with psionic powers, including telekinesis, is also truly gravely mentally ill and not entirely responsible for her actions.")),
                    entry(1009681, new MarvelCharacter(1009681, "U-Go Girl", "After a failed attempt at starting an acting career, Edie Sawyer turned to a life of crime until she learned of a new media savvy team of superhuman mutants named X-Force, and she decided to become a superhero.")),
                    entry(1009682, new MarvelCharacter(1009682, "U.S. Agent", "With the end of the Vietnam War, John Walker thought his dreams of becoming a war hero had also ended, until he learned of the Power Broker, who could give anyone superhuman powers, which Walker used to first become Super-Patriot and later, U.S. Agent.")),
                    entry(1009683, new MarvelCharacter(1009683, "Uatu The Watcher", "Uatu grew so fond of the lifeforms he observed that he occasionally violated his vow of non-interference when Earth's existence was threatened.")),
                    entry(1010358, new MarvelCharacter(1010358, "Ulik", "Ulik was a Rock Troll from the realm known as Nornheim, located underground within the dimension of Asgard.")),
                    entry(1011311, new MarvelCharacter(1011311, "Ultimo", "Ultimo was a robotic construct that was developed several thousand years ago on an unknown world, which the Mandarin eventually discovered and claimed as his own creation.")),
                    entry(1009685, new MarvelCharacter(1009685, "Ultron", "Arguably the greatest and certainly the most horrific creation of scientific genius Dr. Henry Pym, Ultron is a criminally insane rogue sentient robot dedicated to conquest and the extermination of humanity.")),
                    entry(1009686, new MarvelCharacter(1009686, "Umar", "Umar and her sibling Dormammu gathered matter to themselves to increase their power, a practice anathema to their fellow Faltine who consider energy to be superior to matter.")),
                    entry(1010862, new MarvelCharacter(1010862, "Unicorn", "Milos Masaryk, a Soviet intelligence agent assigned as a security guard for Anton Vanko, a Soviet inventor who developed the Crimson Dynamo armor, was tasked by the Soviet government to retrieve Vanko after he defected to the United States.")),
                    entry(1009687, new MarvelCharacter(1009687, "Unus", "Angelo Unuscione is a mutant whose powers did not surface until adolescence, when he first used them as a school bully and later as a small time criminal before immigrating to America and using his ability to create a virtually impenetrable force field around himself to launch a career as a flamboyant, invincible costumed wrestler known by the stage name of Unus the Untouchable.")),
                    entry(1011182, new MarvelCharacter(1011182, "Vampiro", "Vampiro, part of the race known as the Eternals, lived on Earth for many years, eventually taking a wife and making a career for himself as a professional wrestler.")),
                    entry(1011316, new MarvelCharacter(1011316, "Vapor", "Vapor, along with her brother, was among the small group led by Simon Utrecht to simulate the crash that gave the Fantastic Four their powers, and has remained with the U-Foes ever since.")),
                    entry(1009690, new MarvelCharacter(1009690, "Vargas", "Vargas claimed that mutants are deviations from the norm, an evolutionary dead end nature explored until it found the true path for the next step in mutant kinds development, the legitimate Homo Sapiens Superior, namely, himself.")),
                    entry(1010872, new MarvelCharacter(1010872, "Vector", "Simon Utrecht wanted superhuman powers in order to persue personal power and gain, and commissioned a project that would ultimately simulate the crash that gave the Fantastic Four their powers; he has remained with the U-Foes ever since.")),
                    entry(1011231, new MarvelCharacter(1011231, "Veda", "Magdalena Marie Neuntauben became an accomplished martial artist, then a model, and later an actress, from which she donated all of her proceeds to her charity, which made her a prime candidate for recruitment into the Order.")),
                    entry(1009693, new MarvelCharacter(1009693, "Venus Dee Milo", "When Dee Milo was a teenager, her mutant powers manifested, transforming her into a being of energy and seemingly killing her entire family in the resultant explosion, after which she was found by Professor Charles Xavier, mutant mentor and researcher, and Xavier designed a special containment suit that helped her regain some level of humanity.")),
                    entry(1009695, new MarvelCharacter(1009695, "Vindicator", "Heather McNeil-Hudson married James Hudson, founder of Canadian super-team, Alpha Flight, and donned a version of his Vindicator armor after his death.")),
                    entry(1009696, new MarvelCharacter(1009696, "Viper", "After the apparent death of Baron von Strucker, Viper took the name Madame Hydra and took control of the New York-based faction of Hydra.")),
                    entry(1009697, new MarvelCharacter(1009697, "Vision", "The metal monstrosity called Ultron created the synthetic humanoid known as the Vision from the remains of the original android Human Torch of the 1940s to serve as a vehicle of vengeance against the Avengers.")),
                    entry(1010849, new MarvelCharacter(1010849, "Wallflower", "Laurie Collins began to involuntarily manipulate anyone around her once her genetic mutation manifested, unable to control its effects.")),
                    entry(1011267, new MarvelCharacter(1011267, "Wallop", "Walter was born, presumably in the decade of 1910s, into the ClanDestine-- his father, the immortal Adam Destine and his mother a magical genie.")),
                    entry(1009700, new MarvelCharacter(1009700, "Wallow", "Max Pressman murdered his wife and attempted to murder his two children Michael and Melinda, but after police officer shot him before he could so, Pressman returned as a ghost-like entity, with only the face of Melinda's doll as his own.")),
                    entry(1009705, new MarvelCharacter(1009705, "Warpath", "James Proudstar was once a member of Professor X's New Mutants and is currently a member of the X-Men black ops team, X-Force.")),
                    entry(1009706, new MarvelCharacter(1009706, "Warstar", "Warstar, a former member of the Imperial Guard, was one of eight Imperial Guardsmen chosen to battle the team of superhuman Earthling mutants known as the X-Men over the fate of Phoenix, a primal force of the cosmos that had assumed the form of the X-Man Jean Grey.")),
                    entry(1009707, new MarvelCharacter(1009707, "Wasp", "When Janet Van Dyne's father died, she convinced her father's associate Hank Pym to give her a supply of 'Pym particles'; Pym also subjected her to a procedure which granted her the ability to, upon shrinking, grow wings and fire blasts of energy, which she called her 'wasp's stings.'")),
                    entry(1010765, new MarvelCharacter(1010765, "Werewolf By Night", "Jack Russell inherited the curse of lycanthropy from his father, Gregor.")),
                    entry(1010348, new MarvelCharacter(1010348, "Whirlwind", "David Cannon was always a bully, so his mutant abilities naturally led him to a life of crime and petty thievery, until his constant defeat at the hands of the Hank Pym and the Wasp led him to create the Whirlwind identity.")),
                    entry(1009714, new MarvelCharacter(1009714, "Wiccan", "Believing himself to be one of the Scarlet Witch's twin boys, Billy Kaplan also has reality-altering powers and is a member of the Young Avengers.")),
                    entry(1009715, new MarvelCharacter(1009715, "Wild Child", "Kyle Gibney's mutant powers emerged at an early age and left him with a freakish appearance, horrifying his parents, who kicked him out of the house, where he was eventually found and experimented upon by the Secret Empire and, later, Department H, who dubbed Gibney Wild Child and placed him with Gamma Flight, the entry-level team whose recruits can eventually graduate to Alpha Flight.")),
                    entry(1009633, new MarvelCharacter(1009633, "William Stryker", "William Stryker became convinced that Satan had a plot to corrupt humankind by taking over their souls while still in the womb, resulting in their mutations.")),
                    entry(1011009, new MarvelCharacter(1011009, "Wind Dancer", "Given the codename Wind Dancer, Sofia Mantega stepped up to lead the New Mutants.")),
                    entry(1011043, new MarvelCharacter(1011043, "Wither", "When his genetic mutation manifested, Kevin Ford accidentally killed his father with his lethal and uncontrollable touch, after which he was recruited as a student at the Xavier Institute.")),
                    entry(1011290, new MarvelCharacter(1011290, "Wolf Cub", "Nicholas Gleason enrolled at the Xavier Institute after being saved from a pair of mutant-haters by X-Men members Cyclops and Chamber.")),
                    entry(1009717, new MarvelCharacter(1009717, "Wolfsbane", "Rahne Sinclair was an orphan in Scotland, raised by Reverend Craig, who, when her powers manifested, attempted to perform an exorcism to cast out what he perceived was the devil, after which Rahne was rescued by Doctor Moira MacTaggert who legally adopted her, and was introduced to Charles Xavier and enrolled as part of his New Mutants training team.")),
                    entry(1009718, new MarvelCharacter(1009718, "Wolverine", "Born with super-human senses and the power to heal from almost any wound, Wolverine was captured by a secret Canadian organization and given an unbreakable skeleton and claws. Treated like an animal, it took years for him to control himself. Now, he's a premiere member of both the X-Men and the Avengers.")),
                    entry(1009719, new MarvelCharacter(1009719, "Wonder Man", "Simon Williams agreed to undergo an experiment to give him superhuman powers, and Baron Zemo gave him the costumed guise of Wonder Man, warning Simon that he would die without further treatments from Zemo in order to ensure his loyalty, but Simon betrayed Zemo to the Avengers and ultimately joined their ranks.")),
                    entry(1009720, new MarvelCharacter(1009720, "Wong", "When Wong reached adulthood, the Ancient One sent him to the United States to his disciple, Doctor Stephen Strange, where has served Strange loyally and well for many years.")),
                    entry(1010884, new MarvelCharacter(1010884, "Wrecker", "Dirk Garthwaite, the son of a construction worker and abusive father and husband, grew up filled with resentment and anger toward his father, who abandoned the family, and quickly turned to crime, in which he used a crowbar as a reminder of his father, destroying each place he robbed.")),
                    entry(1009722, new MarvelCharacter(1009722, "X-23", "A clone of the mutant Wolverine, X-23 was trained as a living weapon by a secretive government agency. Now residing with the X-Men, she strives to recover her stolen youth and become a fully realized person.")),
                    entry(1009725, new MarvelCharacter(1009725, "X-Man", "A clone of Nathan Summers (Cable), Nate Grey was created in the 'Age of Apocalypse' timeline by that timeline's Mr. Sinister for the sole purpose of destroying Apocalypse.")),
                    entry(1009726, new MarvelCharacter(1009726, "X-Men", "Feared and hated by humans because they're different, the X-Men are heroic mutants, individuals born with special powers who've sworn to use their gifts to protect mutants as well as humans.")),
                    entry(1009736, new MarvelCharacter(1009736, "Yellow Claw", "The Yellow Claw is Plan Tzu, the 19th Century descendant of and rightful successor to the legendary warlord Temujin, a.k.a. Genghis Khan.")),
                    entry(1011163, new MarvelCharacter(1011163, "Zarek", "Zarek is a member of the Kree race with no superhuman abilities or specialized weaponry, but as a blue Kree, he has enhanced strength, stamina and durability.")),
                    entry(1011127, new MarvelCharacter(1011127, "Zodiak", "Twelve demons merged with Norman Harrison, who, soon after, adopted the guise of Zodiac and used his abilities to harness powers based on the astrological Zodiac.")),
                    entry(1011183, new MarvelCharacter(1011183, "Zuras", "Zuras was once the leader of the Eternals.")),
                    entry(1009742, new MarvelCharacter(1009742, "Zzzax", "A chain reaction in an atomic reactor, a result of a terrorist attack, accidentally created a force that absorbed the electrolytes of the nearby humans' brains, granting the explosion of energy a rudimentary sentience."))
                    );
    private static final List<MarvelCharacter> charactersAsList =
            Collections.unmodifiableList(
                    charactersAsMap.values().stream().sorted(Comparator.comparing(c -> c.name)).collect(Collectors.toList())
            );
}
